# CakePoison Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/CakePoison

#==================#
#   Basic Config   #
#==================#
# none :D

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 1.0