##  Plugin Information  ##
name: CakePoison
version: version-number-unknown
main: syam.CakePoison.CakePoison
description: CakePoison Plugin
website: http://sakura-server.net/
##  Original Author     ##
author: syam
commands:
    cakepoison:
      usage: /cakepoison help - to see the help
      aliases: [cake, cp]
      description: To see the CakePoison help.
permissions:
    cakepoison.*:
        default: op
        description: Allow all CakePoison permission.
        children:
            cakepoison.user.*: true
            cakepoison.admin.*: true
    cakepoison.user.*:
        default: op
        description: Allow users CakePoison permission.
        children:
            cakepoison.user.poisoning: true
            cakepoison.user.detoxifying: true
    cakepoison.admin.*:
        default: op
        description: Allow users CakePoison permission.
        children:
            cakepoison.admin.ignore: true
            cakepoison.admin.save: true
            cakepoison.admin.reload: true
    cakepoison.user.poisoning:
        default: op
        description: Allow poisoning cake.
    cakepoison.user.detoxifying:
        default: op
        description: Allow detoxifying poisonous cake.
    cakepoison.admin.ignore:
        default: op
        description: Ignore poisonous cake.
    cakepoison.admin.save:
        default: op
        description: Allow use save command.
    cakepoison.admin.reload:
        default: op
        description: Allow use reload command.
