##  Plugin Information  ##
name: CakePoison
version: version-number-unknown
main: syam.CakePoison.CakePoison
description: CakePoison Plugin
website: http://sakura-server.net/
##  Original Author     ##
author: syam
commands:
    cakepoison:
      usage: /cakepoison help - to see the help
      aliases: [cake, cp]
      description: To see the CakePoison help.
permissions:
    cakepoison.reload:
        default: op
        description: Allow user reload command.
    cakepoison.ignore:
        default: op
        description: Ignore poisonous cake.